### PR TITLE
Montgomery Emacs

### PR DESCRIPTION
**Pull request by larsbrinkhoff**
Copy from Joel N. Chiappa.  
http://ana-3.lcs.mit.edu/~jnc/tech/unix/emacs/

### CODE REVIEW

**Comment by larsbrinkhoff** [comment]
From https://minnie.tuhs.org/pipermail/tuhs/2021-April/023560.html

```
I have also put up the Montgomery Emacs for Unix:

  http://ana-3.lcs.mit.edu/~jnc/tech/unix/emacs

This is the version we were running on the 5th floor MIT V6 machine (CSR),
which by that point have absorbed a few V7isms (e.g. some ioctl() stuff). So
don't expect to be able to compile and run it, without a fair amount of
work. (I vaguely recall that it needs I+D space, so maybe not on a /23 at
all.) But at least the source is in C, so you can read it. I don't think
there's an un-modified version online (i.e. the original Montgomery source),
alas.

**Comment by larsbrinkhoff** [comment]
More from Chiappa:

```
OK, the first 'big' PDP-11 at MIT was an early -11/45 which was for some years
the main undergrad time-sharing machine in the EECS department; it lived
(IIRC) in building 38, where most of the EE department lived. It ran an
MIT-written OS called 'Delphi'; it provided PDP-11 assembler, Algol and LISP
(both interpreted) for the main EECS undergrad programming/language course,
6.031.

Prof. Steve Ward at that time had a group in Tech Sq (where most of the CS
people _actually_ lived) called DSSR (later renamed to RTS). They had an
-11/70 (which lived in a small machine room on the 5th floor, even though
DSSR/RTS was on the 4th floor) which I think initially ran the same OS as the
-11/45 (that would have been before my time). Ward and his group certainly
wrote and ran the EECS -11/45 system.

The -11/70 later ran what I think was the first Unix at MIT (it was certainly
running it by the time I met it, which was my sophmore year). It was V6ish -
actually PWB1, with a lot of stuff that didn't formally appear until V7 -
Typesetter C, adb, make, etc. MIT may have had a formal V6 license, but the
PWB1 stuff 'fell off the back of a truck' via Jon Sieber, who was a member
of the famous Boy Scout troop at Bell Labs.

It was further hacked at MIT - the main change was an almost complete re-write
of the TTY handler, but they also did a new scheduler, added process
suspension (but only with the coopertion of the inferior process), etc.

No direct copy of that machine exists, _but_ we have most of it, because the
CSR group on the 5th floor (the one that was involved in Multics, and later
did a lot of Internet work) had an -11/40 (which they got through DARPA as US
Govt surplus) for their 1 Mbit/sec ring LAN work (which is where I came in -
after taking 6.031, I could program in PDP-11 assembler, which none of the
Multics people in CSR knew anything about). When that got there (shortly
before me), the DSSR Unix was cloned onto it - and we still have a complete
dump of that machine, at the end of its existence.

The CSR machine later became an -11/45; the EECC department got a TOPS-20
machine to be their main time-sharing machine, and wanted an additional -11/40
for a CHAOS front end, so they came to CSR and offered to trade the EECS
-11/45 (the one at the top here) for the CSR -11/40 - which we were happy to
do. (Why they couldn't use the /45 I'm not sure, maybe the DTE20 wouldn't work
with a /45?  In theory it should have, but maybe in practise...) We just got
the CPU, I don't know what happened to the disks, etc.
```

This copy of Montgomery Emacs comes from the CSR machine.

**Comment by larsbrinkhoff** [comment]
From emacs.doc:

```
     This editor was written by	the author  as	an  aide  to  his
other  work, and patterned after the EMACS editor written for the
PDP-10 systems at the M.I.T.  Laboratory  for  Computer	 Science.
The  interface	to  the	user closely follows that provided by the
M.I.T. version,	because	the author was familiar	 with  that  ver-
sion.	The  implementation  of	 EMACS for UNIX	described in this
report was done	by the author, and  is	entirely  different  from
that  used at M.I.T.  The author was not familiar with the imple-
mentation techniques used in the M.I.T.	version,  only	with  the
language in which EMACS	was implemented.

**Comment by larsbrinkhoff** [comment]
Warren was a user on the Mathlab ITS machine, with user name WARREN.

**Comment by jonathangray** [comment]
A scan of a typeset version of "An Interactive Screen Editor for UNIX" recently surfaced:
```
Warren Montgomery
An Interactive Screen Editor for UNIX
June 16, 1980
TM 80-5343-2
```
https://www.tuhs.org/Archive/Documentation/TechReports/USG_Library/1542_An_Interactive_Screen_Editor_For_UNIX.pdf

Earlier than the May 27, 1981, dated
http://ana-3.lcs.mit.edu/~jnc/tech/unix/emacs/emacs.doc

**Pull request merged**
